Add missing schema30 classes for issues#1521 which addresses the last few NoClassDefFoundError errors and cleans up the code a bit around some of the entity class references (will update others later time permitting)
Signed-off-by: Scott Marlow <smarlow@redhat.com>